### ISSUE TITLE
Unrecognized option "form"  under "twig"

### ISSUE THREAD

**Issue by Holicz** [avanzu/AdminThemeBundle#85]
Hi, 

I installed the bundle, but I am not able to install assets and fetch vendor. I get "Unrecognized option "form"  under "twig"".

When I try to run website I've got same error.

InvalidConfigurationException in ArrayNode.php line 314:
Unrecognized option "form" under "twig"

Using Symfony 3, can it be the problem?

**Comment by ripnet** [comment]
Same issue for me with Symfony3

**Comment by avanzu** [comment]
That's due to some changes in the twig bundle. An Update to 1.3.4 should resolve this issue.

**Comment by ripnet** [comment]
Confirmed, 1.3.4 fixed this for me. Thanks @avanzu

**Comment by jibundeyare** [comment]
Hi,

I'm getting the following error because using Symfony 2.3 :
```
  [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
  Unrecognized options "form_theme" under "twig"                                 

Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-update-cmd event terminated with an exception

  [RuntimeException]                                                         
  An error occurred when executing the "'cache:clear --no-warmup'" command.  
```

How am I supposed to manage this ? I forced avanzu/admin-theme-bundle:1.3.3 but this won't do for long...

Im' planning to upgrade to Symfony 2.8 soon but in the meantime, I still need to make my back office work ;)

**Comment by Mangetsu** [comment]
@avanzu I'm enable to update to the specified version due to a conflict with nelmio doc bundle, here is my composer command output : 

> php composer.phar require twig/twig:1.3.*@dev
> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - twig/twig 1.3.0 conflicts with nelmio/api-doc-bundle[2.11.2].
>     - nelmio/api-doc-bundle 2.11.2 conflicts with twig/twig[1.3.0].
>     - twig/twig 1.3.0 conflicts with nelmio/api-doc-bundle[2.11.2].
>     - Installation request for twig/twig 1.3.*@dev -> satisfiable by twig/twig[1.3.0].
>     - Installation request for nelmio/api-doc-bundle == 2.11.2.0 -> satisfiable by nelmio/api-doc-bundle[2.11.2].
> 
> Installation failed, reverting ./composer.json to its original content.

any help to avoid the error "Unrecognized option "form" under "twig" " ?

thank you.

NB: this is my composer info details:

> >php composer.phar info
> cocur/slugify                            v1.4.1                                Converts a string into a slug.
> doctrine/annotations                     v1.2.7                                Docblock Annotations Parser
> doctrine/cache                           v1.6.0                                Caching library offering an object-oriented API for many cache backends
> doctrine/collections                     v1.3.0                                Collections Abstraction library
> doctrine/common                          v2.6.1                                Common Library for Doctrine projects
> doctrine/dbal                            v2.5.4                                Database Abstraction Layer
> doctrine/doctrine-bundle                 1.6.2                                 Symfony DoctrineBundle
> doctrine/doctrine-cache-bundle           1.3.0                                 Symfony Bundle for Doctrine Cache
> doctrine/inflector                       v1.1.0                                Common String Manipulations with regard to casing and singular/plural rules.
> doctrine/instantiator                    1.0.5                                 A small, lightweight utility to instantiate objects in PHP without invoking their constructors
> doctrine/lexer                           v1.0.1                                Base library for a lexer that can be used in Top-Down, Recursive Descent Parsers.
> doctrine/orm                             v2.5.4                                Object-Relational-Mapper for PHP
> friendsofsymfony/rest-bundle             1.7.7                                 This Bundle provides various tools to rapidly develop RESTful API's with Symfony
> friendsofsymfony/user-bundle             dev-master 88f84f6                    Symfony FOSUserBundle
> incenteev/composer-parameter-handler     v2.1.2                                Composer script handling your ignored parameter file
> jdorn/sql-formatter                      v1.2.17                               a PHP SQL highlighting library
> jms/metadata                             1.5.1                                 Class/method/property metadata management in PHP
> jms/parser-lib                           1.0.0                                 A library for easily creating recursive-descent parsers.
> jms/serializer                           1.1.0                                 Library for (de-)serializing data of any complexity; supports XML, JSON, and YAML.
> jms/serializer-bundle                    1.1.0                                 Allows you to easily serialize, and deserialize data of any complexity
> knplabs/knp-menu                         v2.1.1                                An object oriented menu library
> knplabs/knp-menu-bundle                  v2.1.1                                This bundle provides an integration of the KnpMenu library
> michelf/php-markdown                     1.6.0                                 PHP Markdown
> monolog/monolog                          1.18.0                                Sends your logs to files, sockets, inboxes, databases and various web services
> nelmio/api-doc-bundle                    2.11.2                                Generates documentation for your REST API from annotations
> paragonie/random_compat                  v1.2.1                                PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
> phpcollection/phpcollection              0.4.0                                 General-Purpose Collection Library for PHP
> phpoption/phpoption                      1.5.0                                 Option Type for PHP
> psr/log                                  1.0.0                                 Common interface for logging libraries
> sensio/distribution-bundle               v5.0.4                                Base bundle for Symfony Distributions
> sensio/framework-extra-bundle            v3.0.14                               This bundle provides a way to configure your controllers with annotations
> sensio/generator-bundle                  v3.0.6                                This bundle generates code for you
> sensiolabs/security-checker              v3.0.2                                A security checker for your composer.lock
> sonata-project/admin-bundle              dev-master 04c1e81                    Symfony SonataAdminBundle
> sonata-project/block-bundle              2.3.9                                 Symfony SonataBlockBundle
> sonata-project/cache                     1.0.7                                 Cache library
> sonata-project/core-bundle               2.3.10                                Symfony SonataCoreBundle
> sonata-project/datagrid-bundle           2.2                                   Symfony SonataDatagridBundle
> sonata-project/doctrine-extensions       1.0.2                                 Doctrine2 behavioral extensions
> sonata-project/doctrine-orm-admin-bundle dev-master e8eb83f                    Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
> sonata-project/easy-extends-bundle       2.1.10                                Symfony SonataEasyExtendsBundle
> sonata-project/exporter                  1.4.1                                 Lightweight Exporter library
> sonata-project/google-authenticator      1.0.2                                 Library to integrate Google Authenticator into a PHP project
> sonata-project/user-bundle               dev-add_support_for_fos_user2 e119e8e Symfony SonataUserBundle
> swiftmailer/swiftmailer                  v5.4.1                                Swiftmailer, free feature-rich PHP mailer
> symfony/monolog-bundle                   v2.9.0                                Symfony MonologBundle
> symfony/phpunit-bridge                   v3.0.3                                Symfony PHPUnit Bridge
> symfony/polyfill-intl-icu                v1.1.0                                Symfony polyfill for intl's ICU-related data and classes
> symfony/polyfill-mbstring                v1.1.0                                Symfony polyfill for the Mbstring extension
> symfony/polyfill-php56                   v1.1.0                                Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
> symfony/polyfill-php70                   v1.1.0                                Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
> symfony/polyfill-util                    v1.1.0                                Symfony utilities for portability of PHP codes
> symfony/security-acl                     v3.0.0                                Symfony Security Component - ACL (Access Control List)
> symfony/swiftmailer-bundle               v2.3.11                               Symfony SwiftmailerBundle
> symfony/symfony                          v3.0.3                                The Symfony PHP framework
> twig/extensions                          v1.3.0                                Common additional features for Twig that do not directly belong in core
> twig/twig                                v1.24.0                               Twig, the flexible, fast, and secure template language for PHP
> willdurand/jsonp-callback-validator      v1.1.0                                JSONP callback validator.
> willdurand/negotiation                   1.5.0                                 Content Negotiation tools for PHP provided as a standalone library.

**Comment by Saint-Cyr** [comment]
I'm using sonata-project/admin-bundle 3.1.0 and I update to 3.3.0 but it does not solve the issue any help please

**Comment by OskarStark** [comment]
Did you Target the right Project?

Am Dienstag, 14. Juni 2016 schrieb MAPOUKA :

**Comment by matteocng** [comment]
@Mangetsu being unable to update to 1.3.4 and using Symfony >= 2.6,  one could try applying the `AvanzuAdminThemeExtension.php` patch in: 174fd34fba2eaf85344b5dec6a107fca6b135478.

@Saint-Cyr use this in `config.yml` for Symfony >= 2.6

```
twig: 
  form_themes: 
    - something.html.twig
```

instead of this:

```
twig: 
  form: 
    resources: 
      - something.html.twig
```

Docs for the [current](http://symfony.com/doc/current/reference/configuration/twig.html) TwigBundle configuration structure ([old](http://symfony.com/doc/2.5/reference/configuration/twig.html) structure).

**Comment by Saint-Cyr** [comment]
Sorry I'wase confuse a bit it suppose to be Sonata - project sorry !
